# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/thomasmarsh/Documents/Hamilton Thesis Spring 2020/Igor.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(292, 542)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 291, 541))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.single = QtWidgets.QWidget()
        self.single.setObjectName("single")
        self.pushButton = QtWidgets.QPushButton(self.single)
        self.pushButton.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.single)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.single)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 261, 161))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 20, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(180, 10, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(140, 10, 31, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 41, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 41, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(120, 40, 41, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(120, 60, 41, 16))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setGeometry(QtCore.QRect(70, 40, 51, 16))
        self.doubleSpinBox.setDecimals(0)
        self.doubleSpinBox.setMaximum(1e+29)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(70, 60, 51, 16))
        self.doubleSpinBox_2.setDecimals(0)
        self.doubleSpinBox_2.setMaximum(360.0)
        self.doubleSpinBox_2.setSingleStep(45.0)
        self.doubleSpinBox_2.setProperty("value", 225.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(160, 60, 51, 16))
        self.doubleSpinBox_3.setDecimals(2)
        self.doubleSpinBox_3.setMaximum(1e+29)
        self.doubleSpinBox_3.setProperty("value", 0.05)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(160, 40, 51, 16))
        self.doubleSpinBox_4.setDecimals(0)
        self.doubleSpinBox_4.setMaximum(1e+29)
        self.doubleSpinBox_4.setSingleStep(20.0)
        self.doubleSpinBox_4.setProperty("value", 120.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(60, 80, 71, 16))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(130, 80, 31, 16))
        self.spinBox.setMaximum(1)
        self.spinBox.setSingleStep(1)
        self.spinBox.setObjectName("spinBox")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 100, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 100, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 120, 41, 16))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 140, 41, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 120, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setGeometry(QtCore.QRect(50, 140, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(130, 120, 41, 16))
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setGeometry(QtCore.QRect(170, 120, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8.setGeometry(QtCore.QRect(170, 140, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.single)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 230, 261, 31))
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(80, 10, 52, 16))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(150, 10, 61, 16))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.single)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 270, 261, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(10, 70, 71, 16))
        self.label_13.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.label_14.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 110, 111, 16))
        self.label_15.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 130, 111, 16))
        self.label_16.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(10, 150, 81, 16))
        self.label_17.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(120, 10, 81, 16))
        self.doubleSpinBox_5.setDecimals(0)
        self.doubleSpinBox_5.setMaximum(1e+29)
        self.doubleSpinBox_5.setSingleStep(500.0)
        self.doubleSpinBox_5.setProperty("value", 36000.0)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(120, 30, 81, 16))
        self.doubleSpinBox_6.setDecimals(4)
        self.doubleSpinBox_6.setMaximum(0.01)
        self.doubleSpinBox_6.setSingleStep(0.001)
        self.doubleSpinBox_6.setProperty("value", 0.0005)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(120, 50, 81, 16))
        self.doubleSpinBox_7.setDecimals(1)
        self.doubleSpinBox_7.setMinimum(0.3)
        self.doubleSpinBox_7.setMaximum(10.0)
        self.doubleSpinBox_7.setSingleStep(0.1)
        self.doubleSpinBox_7.setProperty("value", 0.5)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_8.setGeometry(QtCore.QRect(120, 70, 81, 16))
        self.doubleSpinBox_8.setDecimals(2)
        self.doubleSpinBox_8.setMinimum(0.0)
        self.doubleSpinBox_8.setMaximum(10.0)
        self.doubleSpinBox_8.setSingleStep(1.0)
        self.doubleSpinBox_8.setProperty("value", 2.07)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_9.setGeometry(QtCore.QRect(120, 90, 81, 16))
        self.doubleSpinBox_9.setDecimals(2)
        self.doubleSpinBox_9.setMinimum(0.0)
        self.doubleSpinBox_9.setMaximum(1.0)
        self.doubleSpinBox_9.setSingleStep(0.02)
        self.doubleSpinBox_9.setProperty("value", 0.06)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_10.setGeometry(QtCore.QRect(120, 110, 81, 16))
        self.doubleSpinBox_10.setDecimals(4)
        self.doubleSpinBox_10.setMinimum(0.0)
        self.doubleSpinBox_10.setMaximum(0.01)
        self.doubleSpinBox_10.setSingleStep(0.0005)
        self.doubleSpinBox_10.setProperty("value", 0.002)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_11.setGeometry(QtCore.QRect(120, 130, 81, 16))
        self.doubleSpinBox_11.setDecimals(0)
        self.doubleSpinBox_11.setMinimum(0.0)
        self.doubleSpinBox_11.setMaximum(100000.0)
        self.doubleSpinBox_11.setSingleStep(100.0)
        self.doubleSpinBox_11.setProperty("value", 1000.0)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_12.setGeometry(QtCore.QRect(120, 150, 81, 16))
        self.doubleSpinBox_12.setDecimals(1)
        self.doubleSpinBox_12.setMinimum(0.1)
        self.doubleSpinBox_12.setMaximum(10.0)
        self.doubleSpinBox_12.setSingleStep(1.0)
        self.doubleSpinBox_12.setProperty("value", 1.0)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.groupBox_4 = QtWidgets.QGroupBox(self.single)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 450, 161, 51))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 10, 61, 16))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_3.setGeometry(QtCore.QRect(60, 30, 91, 16))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_21 = QtWidgets.QLabel(self.single)
        self.label_21.setGeometry(QtCore.QRect(180, 10, 91, 16))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.tabWidget.addTab(self.single, "")
        self.multiple = QtWidgets.QWidget()
        self.multiple.setObjectName("multiple")
        self.label_20 = QtWidgets.QLabel(self.multiple)
        self.label_20.setGeometry(QtCore.QRect(10, 0, 151, 16))
        self.label_20.setObjectName("label_20")
        self.groupBox_5 = QtWidgets.QGroupBox(self.multiple)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 30, 261, 131))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 20, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(110, 40, 91, 16))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.doubleSpinBox_16 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.doubleSpinBox_16.setGeometry(QtCore.QRect(200, 40, 51, 16))
        self.doubleSpinBox_16.setDecimals(0)
        self.doubleSpinBox_16.setMaximum(100.0)
        self.doubleSpinBox_16.setSingleStep(1.0)
        self.doubleSpinBox_16.setProperty("value", 4.0)
        self.doubleSpinBox_16.setObjectName("doubleSpinBox_16")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_7.setGeometry(QtCore.QRect(110, 20, 141, 16))
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 60, 261, 101))
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 20, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_25 = QtWidgets.QLabel(self.groupBox_6)
        self.label_25.setGeometry(QtCore.QRect(130, 10, 71, 16))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_2.setGeometry(QtCore.QRect(210, 10, 41, 16))
        self.spinBox_2.setMaximum(1000)
        self.spinBox_2.setProperty("value", 15)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_3.setGeometry(QtCore.QRect(210, 30, 41, 16))
        self.spinBox_3.setMaximum(1000)
        self.spinBox_3.setProperty("value", 17)
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_26 = QtWidgets.QLabel(self.groupBox_6)
        self.label_26.setGeometry(QtCore.QRect(130, 30, 71, 16))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_6)
        self.label_27.setGeometry(QtCore.QRect(110, 50, 91, 16))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.doubleSpinBox_17 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.doubleSpinBox_17.setGeometry(QtCore.QRect(200, 50, 51, 16))
        self.doubleSpinBox_17.setDecimals(4)
        self.doubleSpinBox_17.setMaximum(0.5)
        self.doubleSpinBox_17.setSingleStep(0.0001)
        self.doubleSpinBox_17.setProperty("value", 0.0)
        self.doubleSpinBox_17.setObjectName("doubleSpinBox_17")
        self.groupBox_7 = QtWidgets.QGroupBox(self.multiple)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 170, 261, 101))
        self.groupBox_7.setObjectName("groupBox_7")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 20, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_28 = QtWidgets.QLabel(self.groupBox_7)
        self.label_28.setGeometry(QtCore.QRect(110, 20, 91, 16))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 40, 261, 61))
        self.groupBox_8.setObjectName("groupBox_8")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 20, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_29 = QtWidgets.QLabel(self.groupBox_8)
        self.label_29.setGeometry(QtCore.QRect(130, 10, 71, 16))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_8)
        self.spinBox_4.setGeometry(QtCore.QRect(210, 10, 41, 16))
        self.spinBox_4.setMaximum(1000)
        self.spinBox_4.setProperty("value", 0)
        self.spinBox_4.setObjectName("spinBox_4")
        self.spinBox_5 = QtWidgets.QSpinBox(self.groupBox_8)
        self.spinBox_5.setGeometry(QtCore.QRect(210, 30, 41, 16))
        self.spinBox_5.setMaximum(1000)
        self.spinBox_5.setProperty("value", 0)
        self.spinBox_5.setObjectName("spinBox_5")
        self.label_30 = QtWidgets.QLabel(self.groupBox_8)
        self.label_30.setGeometry(QtCore.QRect(130, 30, 71, 16))
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_13.setGeometry(QtCore.QRect(50, 40, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.spinBox_6 = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinBox_6.setGeometry(QtCore.QRect(210, 20, 41, 16))
        self.spinBox_6.setMaximum(20)
        self.spinBox_6.setProperty("value", 4)
        self.spinBox_6.setObjectName("spinBox_6")
        self.groupBox_9 = QtWidgets.QGroupBox(self.multiple)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 280, 261, 101))
        self.groupBox_9.setObjectName("groupBox_9")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 20, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_31 = QtWidgets.QLabel(self.groupBox_9)
        self.label_31.setGeometry(QtCore.QRect(110, 20, 91, 16))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_10.setGeometry(QtCore.QRect(0, 40, 261, 61))
        self.groupBox_10.setObjectName("groupBox_10")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_15.setGeometry(QtCore.QRect(10, 20, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_32 = QtWidgets.QLabel(self.groupBox_10)
        self.label_32.setGeometry(QtCore.QRect(130, 10, 71, 16))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.spinBox_7 = QtWidgets.QSpinBox(self.groupBox_10)
        self.spinBox_7.setGeometry(QtCore.QRect(210, 10, 41, 16))
        self.spinBox_7.setMaximum(1000)
        self.spinBox_7.setProperty("value", 0)
        self.spinBox_7.setObjectName("spinBox_7")
        self.spinBox_8 = QtWidgets.QSpinBox(self.groupBox_10)
        self.spinBox_8.setGeometry(QtCore.QRect(210, 30, 41, 16))
        self.spinBox_8.setMaximum(1000)
        self.spinBox_8.setProperty("value", 0)
        self.spinBox_8.setObjectName("spinBox_8")
        self.label_33 = QtWidgets.QLabel(self.groupBox_10)
        self.label_33.setGeometry(QtCore.QRect(130, 30, 71, 16))
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_16.setGeometry(QtCore.QRect(50, 40, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.spinBox_9 = QtWidgets.QSpinBox(self.groupBox_9)
        self.spinBox_9.setGeometry(QtCore.QRect(210, 20, 41, 16))
        self.spinBox_9.setMaximum(20)
        self.spinBox_9.setProperty("value", 4)
        self.spinBox_9.setObjectName("spinBox_9")
        self.groupBox_11 = QtWidgets.QGroupBox(self.multiple)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 389, 261, 51))
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_34 = QtWidgets.QLabel(self.groupBox_11)
        self.label_34.setGeometry(QtCore.QRect(0, 10, 251, 16))
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 30, 241, 16))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_22 = QtWidgets.QLabel(self.multiple)
        self.label_22.setGeometry(QtCore.QRect(190, 10, 91, 16))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.tabWidget.addTab(self.multiple, "")
        self.util = QtWidgets.QWidget()
        self.util.setObjectName("util")
        self.groupBox_12 = QtWidgets.QGroupBox(self.util)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 30, 261, 51))
        self.groupBox_12.setObjectName("groupBox_12")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_17.setGeometry(QtCore.QRect(20, 20, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_35 = QtWidgets.QLabel(self.groupBox_12)
        self.label_35.setGeometry(QtCore.QRect(130, 10, 61, 16))
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.groupBox_12)
        self.doubleSpinBox_13.setGeometry(QtCore.QRect(200, 10, 51, 16))
        self.doubleSpinBox_13.setDecimals(3)
        self.doubleSpinBox_13.setMaximum(10.0)
        self.doubleSpinBox_13.setSingleStep(0.001)
        self.doubleSpinBox_13.setProperty("value", 2.07)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.label_36 = QtWidgets.QLabel(self.groupBox_12)
        self.label_36.setGeometry(QtCore.QRect(130, 30, 61, 16))
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 30, 51, 16))
        self.lineEdit_3.setAcceptDrops(False)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.groupBox_13 = QtWidgets.QGroupBox(self.util)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 90, 261, 41))
        self.groupBox_13.setObjectName("groupBox_13")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_18.setGeometry(QtCore.QRect(20, 20, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_19.setGeometry(QtCore.QRect(140, 20, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.groupBox_14 = QtWidgets.QGroupBox(self.util)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 140, 261, 41))
        self.groupBox_14.setObjectName("groupBox_14")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_20.setGeometry(QtCore.QRect(10, 20, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName("pushButton_20")
        self.spinBox_10 = QtWidgets.QSpinBox(self.groupBox_14)
        self.spinBox_10.setGeometry(QtCore.QRect(130, 20, 42, 16))
        self.spinBox_10.setMaximum(2000)
        self.spinBox_10.setObjectName("spinBox_10")
        self.label_37 = QtWidgets.QLabel(self.groupBox_14)
        self.label_37.setGeometry(QtCore.QRect(90, 20, 41, 16))
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_14)
        self.label_38.setGeometry(QtCore.QRect(170, 20, 41, 16))
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.spinBox_11 = QtWidgets.QSpinBox(self.groupBox_14)
        self.spinBox_11.setGeometry(QtCore.QRect(210, 20, 42, 16))
        self.spinBox_11.setMaximum(2000)
        self.spinBox_11.setProperty("value", 500)
        self.spinBox_11.setObjectName("spinBox_11")
        self.groupBox_15 = QtWidgets.QGroupBox(self.util)
        self.groupBox_15.setGeometry(QtCore.QRect(10, 190, 261, 41))
        self.groupBox_15.setObjectName("groupBox_15")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_21.setGeometry(QtCore.QRect(20, 20, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_22.setGeometry(QtCore.QRect(140, 20, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName("pushButton_22")
        self.groupBox_16 = QtWidgets.QGroupBox(self.util)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 240, 261, 61))
        self.groupBox_16.setObjectName("groupBox_16")
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_16)
        self.pushButton_23.setGeometry(QtCore.QRect(10, 20, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_16)
        self.pushButton_24.setGeometry(QtCore.QRect(190, 20, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox_16)
        self.pushButton_25.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.groupBox_16)
        self.pushButton_26.setGeometry(QtCore.QRect(190, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.groupBox_16)
        self.pushButton_27.setGeometry(QtCore.QRect(100, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setObjectName("pushButton_27")
        self.groupBox_17 = QtWidgets.QGroupBox(self.util)
        self.groupBox_17.setGeometry(QtCore.QRect(10, 310, 261, 61))
        self.groupBox_17.setObjectName("groupBox_17")
        self.pushButton_28 = QtWidgets.QPushButton(self.groupBox_17)
        self.pushButton_28.setGeometry(QtCore.QRect(10, 20, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName("pushButton_28")
        self.spinBox_12 = QtWidgets.QSpinBox(self.groupBox_17)
        self.spinBox_12.setGeometry(QtCore.QRect(120, 20, 31, 16))
        self.spinBox_12.setMaximum(8)
        self.spinBox_12.setObjectName("spinBox_12")
        self.label_39 = QtWidgets.QLabel(self.groupBox_17)
        self.label_39.setGeometry(QtCore.QRect(90, 20, 31, 16))
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.label_41 = QtWidgets.QLabel(self.groupBox_17)
        self.label_41.setGeometry(QtCore.QRect(160, 20, 51, 16))
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.spinBox_14 = QtWidgets.QSpinBox(self.groupBox_17)
        self.spinBox_14.setGeometry(QtCore.QRect(220, 20, 31, 16))
        self.spinBox_14.setMaximum(1)
        self.spinBox_14.setObjectName("spinBox_14")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_17)
        self.lineEdit_4.setEnabled(True)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.lineEdit_4.setAcceptDrops(False)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_42 = QtWidgets.QLabel(self.groupBox_17)
        self.label_42.setGeometry(QtCore.QRect(160, 40, 51, 16))
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.label_40 = QtWidgets.QLabel(self.groupBox_17)
        self.label_40.setGeometry(QtCore.QRect(90, 40, 31, 16))
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.spinBox_13 = QtWidgets.QSpinBox(self.groupBox_17)
        self.spinBox_13.setGeometry(QtCore.QRect(120, 40, 31, 16))
        self.spinBox_13.setMaximum(8)
        self.spinBox_13.setObjectName("spinBox_13")
        self.spinBox_15 = QtWidgets.QSpinBox(self.groupBox_17)
        self.spinBox_15.setGeometry(QtCore.QRect(220, 40, 31, 16))
        self.spinBox_15.setMaximum(1)
        self.spinBox_15.setObjectName("spinBox_15")
        self.groupBox_18 = QtWidgets.QGroupBox(self.util)
        self.groupBox_18.setGeometry(QtCore.QRect(10, 380, 261, 91))
        self.groupBox_18.setObjectName("groupBox_18")
        self.pushButton_29 = QtWidgets.QPushButton(self.groupBox_18)
        self.pushButton_29.setGeometry(QtCore.QRect(10, 20, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.groupBox_18)
        self.pushButton_30.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setObjectName("pushButton_30")
        self.label_43 = QtWidgets.QLabel(self.groupBox_18)
        self.label_43.setGeometry(QtCore.QRect(100, 10, 61, 16))
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_18)
        self.lineEdit_5.setGeometry(QtCore.QRect(160, 10, 91, 16))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_44 = QtWidgets.QLabel(self.groupBox_18)
        self.label_44.setGeometry(QtCore.QRect(100, 30, 31, 16))
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.groupBox_18)
        self.label_45.setGeometry(QtCore.QRect(100, 50, 31, 16))
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_18)
        self.lineEdit_6.setGeometry(QtCore.QRect(130, 30, 121, 16))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_18)
        self.lineEdit_7.setGeometry(QtCore.QRect(130, 50, 121, 16))
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_18)
        self.lineEdit_8.setEnabled(True)
        self.lineEdit_8.setGeometry(QtCore.QRect(160, 70, 51, 16))
        self.lineEdit_8.setAcceptDrops(False)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_46 = QtWidgets.QLabel(self.groupBox_18)
        self.label_46.setGeometry(QtCore.QRect(110, 70, 41, 16))
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.label_23 = QtWidgets.QLabel(self.util)
        self.label_23.setGeometry(QtCore.QRect(180, 10, 91, 16))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.tabWidget.addTab(self.util, "")
        self.coil = QtWidgets.QWidget()
        self.coil.setObjectName("coil")
        self.groupBox_19 = QtWidgets.QGroupBox(self.coil)
        self.groupBox_19.setGeometry(QtCore.QRect(10, 30, 261, 91))
        self.groupBox_19.setObjectName("groupBox_19")
        self.pushButton_31 = QtWidgets.QPushButton(self.groupBox_19)
        self.pushButton_31.setGeometry(QtCore.QRect(20, 50, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setObjectName("pushButton_31")
        self.label_47 = QtWidgets.QLabel(self.groupBox_19)
        self.label_47.setGeometry(QtCore.QRect(110, 30, 61, 16))
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.groupBox_19)
        self.label_48.setGeometry(QtCore.QRect(10, 10, 241, 16))
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.spinBox_16 = QtWidgets.QSpinBox(self.groupBox_19)
        self.spinBox_16.setGeometry(QtCore.QRect(170, 30, 61, 16))
        self.spinBox_16.setMinimum(1000)
        self.spinBox_16.setMaximum(400000)
        self.spinBox_16.setSingleStep(1000)
        self.spinBox_16.setProperty("value", 20000)
        self.spinBox_16.setObjectName("spinBox_16")
        self.spinBox_17 = QtWidgets.QSpinBox(self.groupBox_19)
        self.spinBox_17.setGeometry(QtCore.QRect(170, 50, 61, 16))
        self.spinBox_17.setMinimum(1000)
        self.spinBox_17.setMaximum(400000)
        self.spinBox_17.setSingleStep(1000)
        self.spinBox_17.setProperty("value", 45000)
        self.spinBox_17.setObjectName("spinBox_17")
        self.label_49 = QtWidgets.QLabel(self.groupBox_19)
        self.label_49.setGeometry(QtCore.QRect(110, 50, 61, 16))
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.spinBox_18 = QtWidgets.QSpinBox(self.groupBox_19)
        self.spinBox_18.setGeometry(QtCore.QRect(170, 70, 61, 16))
        self.spinBox_18.setMinimum(10)
        self.spinBox_18.setMaximum(400000)
        self.spinBox_18.setSingleStep(1000)
        self.spinBox_18.setProperty("value", 1000)
        self.spinBox_18.setObjectName("spinBox_18")
        self.label_50 = QtWidgets.QLabel(self.groupBox_19)
        self.label_50.setGeometry(QtCore.QRect(110, 70, 61, 16))
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.groupBox_20 = QtWidgets.QGroupBox(self.coil)
        self.groupBox_20.setGeometry(QtCore.QRect(10, 130, 261, 31))
        self.groupBox_20.setObjectName("groupBox_20")
        self.label_51 = QtWidgets.QLabel(self.groupBox_20)
        self.label_51.setGeometry(QtCore.QRect(10, 10, 241, 16))
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.coil)
        self.label_52.setGeometry(QtCore.QRect(180, 10, 91, 16))
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.tabWidget.addTab(self.coil, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Run NIFID"))
        self.label.setText(_translate("Form", "Single NIFID Controls"))
        self.groupBox.setTitle(_translate("Form", "Single Sweep Fitting"))
        self.pushButton_2.setText(_translate("Form", "Fit Single Sweep"))
        self.lineEdit.setText(_translate("Form", "name"))
        self.label_2.setText(_translate("Form", "Name"))
        self.label_3.setText(_translate("Form", "Amp (mV)"))
        self.label_4.setText(_translate("Form", "Phase"))
        self.label_5.setText(_translate("Form", "Freq"))
        self.label_6.setText(_translate("Form", "T2"))
        self.label_7.setText(_translate("Form", "Relative Phase "))
        self.pushButton_3.setText(_translate("Form", "Test Params"))
        self.pushButton_4.setText(_translate("Form", "Set Params to Fit"))
        self.checkBox.setText(_translate("Form", "Show"))
        self.checkBox_2.setText(_translate("Form", "Show"))
        self.pushButton_5.setText(_translate("Form", "FFT Graph"))
        self.pushButton_6.setText(_translate("Form", "Raw Graph"))
        self.checkBox_3.setText(_translate("Form", "Show"))
        self.pushButton_7.setText(_translate("Form", "R Graph"))
        self.pushButton_8.setText(_translate("Form", "Raw FFT"))
        self.groupBox_2.setTitle(_translate("Form", "Fit Type"))
        self.comboBox.setItemText(0, _translate("Form", "Poly"))
        self.comboBox.setItemText(1, _translate("Form", "Exp"))
        self.comboBox.setItemText(2, _translate("Form", "SineX"))
        self.comboBox.setItemText(3, _translate("Form", "SineXY"))
        self.label_8.setText(_translate("Form", "Fit Type to Use"))
        self.label_9.setText(_translate("Form", "flag="))
        self.groupBox_3.setTitle(_translate("Form", "NIFID Parameters"))
        self.label_10.setText(_translate("Form", "Frequency (Hz)"))
        self.label_11.setText(_translate("Form", "Pulse Length (S)"))
        self.label_12.setText(_translate("Form", "RF Amplitude (V)"))
        self.label_13.setText(_translate("Form", "B Field (V)"))
        self.label_14.setText(_translate("Form", "Readout Time"))
        self.label_15.setText(_translate("Form", "Additional Mute Time (S)"))
        self.label_16.setText(_translate("Form", "Lowpass Filter (Hz)"))
        self.label_17.setText(_translate("Form", "Signal Range"))
        self.groupBox_4.setTitle(_translate("Form", "Hardware"))
        self.label_18.setText(_translate("Form", "Lock-In Mode"))
        self.label_19.setText(_translate("Form", "RF Mode"))
        self.comboBox_2.setItemText(0, _translate("Form", "Computer"))
        self.comboBox_2.setItemText(1, _translate("Form", "Mixer"))
        self.comboBox_2.setItemText(2, _translate("Form", "LockIn"))
        self.comboBox_3.setItemText(0, _translate("Form", "NI Board"))
        self.comboBox_3.setItemText(1, _translate("Form", "GPID Func. Gen."))
        self.label_21.setText(_translate("Form", "NIFIDscanNum 17"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.single), _translate("Form", "Single"))
        self.label_20.setText(_translate("Form", "Spin Down / Pump Rate / NMR Loss"))
        self.groupBox_5.setTitle(_translate("Form", "Spin Down"))
        self.pushButton_9.setText(_translate("Form", "Start Spin Down"))
        self.label_24.setText(_translate("Form", "Time Interval (hrs)"))
        self.checkBox_7.setText(_translate("Form", "Wait 1 Hour Before Spin Down"))
        self.groupBox_6.setTitle(_translate("Form", "Spin Down Fitting"))
        self.pushButton_10.setText(_translate("Form", "Fit Spin Down Data"))
        self.label_25.setText(_translate("Form", "First Scan Num"))
        self.label_26.setText(_translate("Form", "Last Scan Num"))
        self.label_27.setText(_translate("Form", "NMR Loss (not %)"))
        self.groupBox_7.setTitle(_translate("Form", "NMR Loss"))
        self.pushButton_11.setText(_translate("Form", "Start NMR Loss"))
        self.label_28.setText(_translate("Form", "Number of Sweeps"))
        self.groupBox_8.setTitle(_translate("Form", "NMR Loss Fitting"))
        self.pushButton_12.setText(_translate("Form", "Fit NMR Loss Data"))
        self.label_29.setText(_translate("Form", "First Scan Num"))
        self.label_30.setText(_translate("Form", "Last Scan Num"))
        self.pushButton_13.setText(_translate("Form", "Show Table"))
        self.groupBox_9.setTitle(_translate("Form", "Pump Rate"))
        self.pushButton_14.setText(_translate("Form", "Start Pump Rate"))
        self.label_31.setText(_translate("Form", "Number of Sweeps"))
        self.groupBox_10.setTitle(_translate("Form", "Pump Rate Fitting"))
        self.pushButton_15.setText(_translate("Form", "Fit Pump Rate"))
        self.label_32.setText(_translate("Form", "First Scan Num"))
        self.label_33.setText(_translate("Form", "Last Scan Num"))
        self.pushButton_16.setText(_translate("Form", "Rate Table"))
        self.groupBox_11.setTitle(_translate("Form", "Ignore Data Waves During Fits"))
        self.label_34.setText(_translate("Form", "Scan nums separated by commas to ignore in all fits"))
        self.label_22.setText(_translate("Form", "NIFIDscanNum 17"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.multiple), _translate("Form", "Multiple"))
        self.groupBox_12.setTitle(_translate("Form", "Magnetic Field Control"))
        self.pushButton_17.setText(_translate("Form", "Set Field"))
        self.label_35.setText(_translate("Form", "New Voltage"))
        self.label_36.setText(_translate("Form", "Current Value"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "2.07"))
        self.groupBox_13.setTitle(_translate("Form", "Utilities"))
        self.pushButton_18.setText(_translate("Form", "NMR History Table"))
        self.pushButton_19.setText(_translate("Form", "Save History File"))
        self.groupBox_14.setTitle(_translate("Form", "Kill Data Waves"))
        self.pushButton_20.setText(_translate("Form", "KillDataWaves"))
        self.label_37.setText(_translate("Form", "Start"))
        self.label_38.setText(_translate("Form", "End"))
        self.groupBox_15.setTitle(_translate("Form", "Flip Polarization"))
        self.pushButton_21.setText(_translate("Form", "B-Sweep AFP Panel"))
        self.pushButton_22.setText(_translate("Form", "F-Sweep AFP Panel"))
        self.groupBox_16.setTitle(_translate("Form", "Initialization"))
        self.pushButton_23.setText(_translate("Form", "NIFID Init"))
        self.pushButton_24.setText(_translate("Form", "General Init"))
        self.pushButton_25.setText(_translate("Form", "DIO Init"))
        self.pushButton_26.setText(_translate("Form", "NIDAQ Error"))
        self.pushButton_27.setText(_translate("Form", "NIDAQ Reset"))
        self.groupBox_17.setTitle(_translate("Form", "NIDAQ"))
        self.pushButton_28.setText(_translate("Form", "Set DIO Chan"))
        self.label_39.setText(_translate("Form", "Chan"))
        self.label_41.setText(_translate("Form", "Value (0/1)"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "Read DIO Chan"))
        self.label_42.setText(_translate("Form", "Value (0/1)"))
        self.label_40.setText(_translate("Form", "Chan"))
        self.groupBox_18.setTitle(_translate("Form", "GPIB"))
        self.pushButton_29.setText(_translate("Form", "Write"))
        self.pushButton_30.setText(_translate("Form", "Read"))
        self.label_43.setText(_translate("Form", "Device Name"))
        self.label_44.setText(_translate("Form", "String"))
        self.label_45.setText(_translate("Form", "String"))
        self.lineEdit_8.setPlaceholderText(_translate("Form", "0"))
        self.label_46.setText(_translate("Form", "Response"))
        self.label_23.setText(_translate("Form", "NIFIDscanNum 17"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.util), _translate("Form", "Utilities"))
        self.groupBox_19.setTitle(_translate("Form", "Find Q for Coil"))
        self.pushButton_31.setText(_translate("Form", "Q Sweep"))
        self.label_47.setText(_translate("Form", "Q Start Freq."))
        self.label_48.setText(_translate("Form", "Make sure that you change the field first!"))
        self.label_49.setText(_translate("Form", "Q Start Freq."))
        self.label_50.setText(_translate("Form", "Q Start Freq."))
        self.groupBox_20.setTitle(_translate("Form", "Other Comments"))
        self.label_51.setText(_translate("Form", "-- See \"LoopInductance()\" at the end of the code"))
        self.label_52.setText(_translate("Form", "NIFIDscanNum 17"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.coil), _translate("Form", "Coil Utilities"))


